image:
  repository: framjet/eso-cluster-secret-store-per-ns
  tag: main
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: eso-cluster-secret-store-per-ns
  annotations: {}

rbac:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

clusterSecretStore:
  # Enable/disable the default template ConfigMap
  create: true
  # Name of the template ConfigMap (defaults to <release-name>-template if not specified)
  name: ""
  # Prefix for the ClusterSecretStore resource name
  namePrefix: "k8s-"
  # Default template configuration
  template:
    caProvider:
      type: ConfigMap
      name: kube-root-ca.crt
      key: ca.crt
      namespace: external-secrets
    auth:
      serviceAccount:
        name: external-secrets
        namespace: external-secrets

# Label configuration for namespace detection
label:
  # The label key to watch for
  key: "k8s.framjet.dev/eso-cluster-secret-store-per-ns"
  # The label value that triggers ClusterSecretStore creation
  value: "true"

# Cleanup configuration
cleanup:
  # Whether to delete ClusterSecretStore resources when the operator is deleted
  onDelete: true
  # Whether to process existing namespaces on operator startup
  processExisting: true 